version: '3.8'

services:
  db:
    container_name: db
    image:  mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    tty: true
    ports:
      - 3306:3306
    env_file:
      - ./.env

  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    entrypoint: wait-for db:3306 -t 40 -- node index.js
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

volumes:
  db:
    driver: local